name: Build Cordova APK
on: [push, workflow_dispatch]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java (JDK 11)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Prepare and Build Cordova
        run: |
          # 1. Buat proyek
          cordova create my_app com.kamu.resizer ResizerApp
          
          # 2. Sinkronkan file kamu
          rm -rf my_app/www/*
          cp -r www/* my_app/www/
          cp config.xml my_app/config.xml
          
          cd my_app
          # 3. GUNAKAN VERSI INI UNTUK ANDROID 13
          cordova platform add android@12.0.0
          
          # 4. Tambahkan izin akses media agar bisa buka galeri di Android 13
          cordova plugin add cordova-plugin-chooser
          
          # 5. Jalankan Build
          cordova build android --debug --device
          
          mkdir -p ../output
          cp platforms/android/app/build/outputs/apk/debug/app-debug.apk ../output/resizer-android13.apk

      - name: Upload APK Result
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-Resizer-Android13
          path: output/resizer-android13.apk
